### PR TITLE
added demandbase tag

### PR DESCRIPTION
**Pull request by matthewscheer**
added demandbase tag to footer

looks right in my dev env

however, i don't have access to demandbase dashboard / admin area so no idea if the script works or not. This is what they gave us to add to the website.

### CODE REVIEW

**Comment by matthewscheer** [comment]
@oskapt Can this go live today? Tom wants the website data to start collecting so the campaign can launch early next week.

**Comment by oskapt** [comment]
Please put this into `layouts/partials/tracking.html` instead of directly in the footer. Add the new commit, and let me know, and I'll review it again.

**Comment by matthewscheer** [comment]
@oskapt The instructions from demandbase said this particular demandbase script needed to go right before `</body>` ...will the tracking.html partial insert the script there?

**Comment by oskapt** [comment]
it honestly doesn't really matter, but if you look at the code, everything in `tracking.html` is inserted just above where you put your snippet. the fact that the `addthis` stuff is in between doesn't matter.

```
 {{ partial "tracking.html" . }}	{{ partial "tracking.html" . }}
{{ partial "addthis-script" . }}	{{ partial "addthis-script" . }}

 <!--demandbase tag-->
```

**Comment by matthewscheer** [comment]
oh i see! ok cool. will move the demandbase script to tracking partial right after k3s online training, so in about 2 hours.

**Comment by matthewscheer** [comment]
@oskapt Moved the demandbase tag to the tracking.html partial as you requested.

**Pull request merged**
